import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import Button from 'react-bootstrap/Button'
import Form from 'react-bootstrap/Form'
import InputGroup from 'react-bootstrap/InputGroup'

import heroImg from '../public/hero.svg'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Goldwire JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Container className="py-4">
        <header className="pb-3 mb-4 border-bottom">
          <a href="/" className="d-flex align-items-center text-dark text-decoration-none">
            <span className="fs-4">Goldwire JS</span>
          </a>
        </header>

        <div className="p-5 mb-4 bg-light rounded-3">
          <div style={{ position: 'relative' }} className="container-fluid py-5">
            <Image
              src={heroImg}
              alt="Goldwire ts"
              layout="fill"
              objectFit="cover"
              quality={100}
            />
            <h1 className="display-5 fw-bold">Lorem ipsum</h1>
            <p className="col-md-8 fs-4">
              dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </p>
            <Button as="a" variant="warning" type="button">Iscriviti!</Button>
          </div>
        </div>

        <div className="p-5 mb-4">
          <Form>
            <Row className="align-items-center">
              <Col md={10}>
                <Form.Label htmlFor="inlineFormInput" visuallyHidden>
                  Name
                </Form.Label>
                <InputGroup className="mb-2">
                  <InputGroup.Text>@</InputGroup.Text>
                  <Form.Control id="inlineFormInputGroup" placeholder="inserisci un indirizzo email" />
                </InputGroup>
              </Col>
              <Col md={2}>
                <Button type="submit" variant="warning" className="mb-2">
                  Iscriviti
                </Button>
              </Col>
            </Row>
          </Form>
        </div>

        <Row className="align-items-md-stretch">
          <Col md={6}>
            <div className="h-100 p-5 text-white bg-dark rounded-3">
              <h2>Excepteur sint occaecat</h2>
              <p>
              quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>  
            </div>
          </Col>
          <Col md={6}>
            <div className="h-100 p-5 bg-warning border rounded-3">
              <h2>At vero eos et accusamus et iusto</h2>
              <p>
              Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus.  
              </p>
            </div>
          </Col>
        </Row>

        <footer className="pt-3 mt-4 text-muted border-top">
          &copy; 2021
        </footer>
      </Container>
    </>
  )
}

export default Home
